name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        default: 'alpha'

env:
  # Common users. We can't run a step 'if secrets.GITHUB_TOKEN != ""' but we can run
  # a step 'if env.GITHUB_TOKEN' != ""', so we copy these to succinctly test whether
  # credentials have been provided before trying to run steps that need them.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  promote-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        if: env.GITHUB_TOKEN != ''
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Artifacts Github Container Registry
        if: env.GITHUB_TOKEN != ''
        run: make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
        env:
          VERSION: ${{ github.event.inputs.version }}
          CHANNEL: ${{ github.event.inputs.channel }}
